name: Build and Push Docker image

on:
  push:
    branches:
      - main  # Change to your branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: echo "${{ secrets.password }}" | docker login -u "${{ secrets.username }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t sandiriamulya/gitdocker:latest .
        docker push sandiriamulya/gitdocker:latest
